// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workspace IDs that ChatGPT auth is allowed to use.
 *
 * This accepts the historical single-string config form as well as a list of
 * allowed workspace IDs.
 */
export type ForcedChatgptWorkspaceIds = string | Array<string>;
